// Mocks generated by Mockito 5.0.15 from annotations
// in ml_algo/test/mocks.dart.
// Do not manually edit this file.

import 'dart:async' as _i50;
import 'dart:collection' as _i14;
import 'dart:io' as _i18;

import 'package:ml_algo/ml_algo.dart' as _i11;
import 'package:ml_algo/src/classifier/classifier.dart' as _i48;
import 'package:ml_algo/src/classifier/decision_tree_classifier/decision_tree_classifier_factory.dart'
    as _i42;
import 'package:ml_algo/src/classifier/knn_classifier/knn_classifier_factory.dart'
    as _i53;
import 'package:ml_algo/src/classifier/logistic_regressor/logistic_regressor_factory.dart'
    as _i68;
import 'package:ml_algo/src/classifier/softmax_regressor/softmax_regressor_factory.dart'
    as _i65;
import 'package:ml_algo/src/common/distribution_calculator/distribution_calculator.dart'
    as _i15;
import 'package:ml_algo/src/common/distribution_calculator/distribution_calculator_factory.dart'
    as _i44;
import 'package:ml_algo/src/cost_function/cost_function.dart' as _i10;
import 'package:ml_algo/src/cost_function/cost_function_factory.dart' as _i40;
import 'package:ml_algo/src/cost_function/cost_function_type.dart' as _i41;
import 'package:ml_algo/src/knn_kernel/kernel.dart' as _i20;
import 'package:ml_algo/src/knn_kernel/kernel_factory.dart' as _i52;
import 'package:ml_algo/src/knn_solver/knn_solver.dart' as _i19;
import 'package:ml_algo/src/knn_solver/knn_solver_factory.dart' as _i51;
import 'package:ml_algo/src/knn_solver/neigbour.dart' as _i49;
import 'package:ml_algo/src/linear_optimizer/convergence_detector/convergence_detector.dart'
    as _i23;
import 'package:ml_algo/src/linear_optimizer/convergence_detector/convergence_detector_factory.dart'
    as _i55;
import 'package:ml_algo/src/linear_optimizer/gradient_optimizer/learning_rate/learning_rate_iterable_factory.dart'
    as _i45;
import 'package:ml_algo/src/linear_optimizer/initial_coefficients_generator/initial_coefficients_generator.dart'
    as _i13;
import 'package:ml_algo/src/linear_optimizer/initial_coefficients_generator/initial_coefficients_generator_factory.dart'
    as _i43;
import 'package:ml_algo/src/linear_optimizer/linear_optimizer.dart' as _i22;
import 'package:ml_algo/src/linear_optimizer/linear_optimizer_factory.dart'
    as _i54;
import 'package:ml_algo/src/link_function/link_function.dart' as _i28;
import 'package:ml_algo/src/math/randomizer/randomizer.dart' as _i8;
import 'package:ml_algo/src/math/randomizer/randomizer_factory.dart' as _i39;
import 'package:ml_algo/src/metric/metric.dart' as _i7;
import 'package:ml_algo/src/metric/metric_factory.dart' as _i37;
import 'package:ml_algo/src/metric/metric_type.dart' as _i38;
import 'package:ml_algo/src/model_selection/assessable.dart' as _i58;
import 'package:ml_algo/src/model_selection/model_assessor/classifier_assessor.dart'
    as _i47;
import 'package:ml_algo/src/model_selection/split_indices_provider/split_indices_provider.dart'
    as _i24;
import 'package:ml_algo/src/model_selection/split_indices_provider/split_indices_provider_factory.dart'
    as _i56;
import 'package:ml_algo/src/model_selection/split_indices_provider/split_indices_provider_type.dart'
    as _i57;
import 'package:ml_algo/src/predictor/predictor.dart' as _i66;
import 'package:ml_algo/src/regressor/knn_regressor/knn_regressor_factory.dart'
    as _i64;
import 'package:ml_algo/src/regressor/linear_regressor/linear_regressor_factory.dart'
    as _i67;
import 'package:ml_algo/src/tree_trainer/decision_tree_trainer.dart' as _i63;
import 'package:ml_algo/src/tree_trainer/leaf_detector/leaf_detector.dart'
    as _i17;
import 'package:ml_algo/src/tree_trainer/leaf_detector/leaf_detector_factory.dart'
    as _i46;
import 'package:ml_algo/src/tree_trainer/leaf_label/leaf_label.dart' as _i16;
import 'package:ml_algo/src/tree_trainer/leaf_label/leaf_label_factory.dart'
    as _i25;
import 'package:ml_algo/src/tree_trainer/leaf_label/leaf_label_factory_factory.dart'
    as _i59;
import 'package:ml_algo/src/tree_trainer/leaf_label/leaf_label_factory_type.dart'
    as _i60;
import 'package:ml_algo/src/tree_trainer/split_assessor/split_assessor.dart'
    as _i5;
import 'package:ml_algo/src/tree_trainer/split_assessor/split_assessor_factory.dart'
    as _i33;
import 'package:ml_algo/src/tree_trainer/split_assessor/split_assessor_type.dart'
    as _i34;
import 'package:ml_algo/src/tree_trainer/split_selector/split_selector.dart'
    as _i26;
import 'package:ml_algo/src/tree_trainer/split_selector/split_selector_factory.dart'
    as _i61;
import 'package:ml_algo/src/tree_trainer/split_selector/split_selector_type.dart'
    as _i62;
import 'package:ml_algo/src/tree_trainer/splitter/nominal_splitter/nominal_splitter.dart'
    as _i3;
import 'package:ml_algo/src/tree_trainer/splitter/nominal_splitter/nominal_splitter_factory.dart'
    as _i30;
import 'package:ml_algo/src/tree_trainer/splitter/numerical_splitter/numerical_splitter.dart'
    as _i2;
import 'package:ml_algo/src/tree_trainer/splitter/numerical_splitter/numerical_splitter_factory.dart'
    as _i29;
import 'package:ml_algo/src/tree_trainer/splitter/splitter.dart' as _i6;
import 'package:ml_algo/src/tree_trainer/splitter/splitter_factory.dart'
    as _i35;
import 'package:ml_algo/src/tree_trainer/splitter/splitter_type.dart' as _i36;
import 'package:ml_algo/src/tree_trainer/tree_node/decision_tree_node/decision_tree_node.dart'
    as _i27;
import 'package:ml_algo/src/tree_trainer/tree_node/intermediate_tree_node_factory.dart'
    as _i31;
import 'package:ml_algo/src/tree_trainer/tree_node/splitting_predicate/tree_node_splitting_predicate_type.dart'
    as _i32;
import 'package:ml_algo/src/tree_trainer/tree_node/tree_node.dart' as _i4;
import 'package:ml_dataframe/ml_dataframe.dart' as _i21;
import 'package:ml_linalg/linalg.dart' as _i12;
import 'package:ml_linalg/matrix.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeNumericalTreeSplitter_0 extends _i1.Fake
    implements _i2.NumericalTreeSplitter {}

class _FakeNominalTreeSplitter_1 extends _i1.Fake
    implements _i3.NominalTreeSplitter {}

class _FakeTreeNode_2 extends _i1.Fake implements _i4.TreeNode {}

class _FakeTreeSplitAssessor_3 extends _i1.Fake
    implements _i5.TreeSplitAssessor {}

class _FakeTreeSplitter_4 extends _i1.Fake implements _i6.TreeSplitter {}

class _FakeMetric_5 extends _i1.Fake implements _i7.Metric {}

class _FakeRandomizer_6 extends _i1.Fake implements _i8.Randomizer {}

class _FakeMatrix_7 extends _i1.Fake implements _i9.Matrix {}

class _FakeCostFunction_8 extends _i1.Fake implements _i10.CostFunction {}

class _FakeDecisionTreeClassifier_9 extends _i1.Fake
    implements _i11.DecisionTreeClassifier {}

class _FakeVector_10 extends _i1.Fake implements _i12.Vector {}

class _FakeInitialCoefficientsGenerator_11 extends _i1.Fake
    implements _i13.InitialCoefficientsGenerator {}

class _FakeHashMap_12<K, V> extends _i1.Fake implements _i14.HashMap<K, V> {}

class _FakeDistributionCalculator_13 extends _i1.Fake
    implements _i15.DistributionCalculator {}

class _FakeTreeLeafLabel_14 extends _i1.Fake implements _i16.TreeLeafLabel {}

class _FakeTreeLeafDetector_15 extends _i1.Fake
    implements _i17.TreeLeafDetector {}

class _FakeFile_16 extends _i1.Fake implements _i18.File {}

class _FakeKnnSolver_17 extends _i1.Fake implements _i19.KnnSolver {}

class _FakeKernel_18 extends _i1.Fake implements _i20.Kernel {}

class _FakeKnnClassifier_19 extends _i1.Fake implements _i11.KnnClassifier {}

class _FakeDataFrame_20 extends _i1.Fake implements _i21.DataFrame {}

class _FakeLinearOptimizer_21 extends _i1.Fake implements _i22.LinearOptimizer {
}

class _FakeConvergenceDetector_22 extends _i1.Fake
    implements _i23.ConvergenceDetector {}

class _FakeSplitIndicesProvider_23 extends _i1.Fake
    implements _i24.SplitIndicesProvider {}

class _FakeTreeLeafLabelFactory_24 extends _i1.Fake
    implements _i25.TreeLeafLabelFactory {}

class _FakeTreeSplitSelector_25 extends _i1.Fake
    implements _i26.TreeSplitSelector {}

class _FakeDecisionTreeNode_26 extends _i1.Fake
    implements _i27.DecisionTreeNode {}

class _FakeKnnRegressor_27 extends _i1.Fake implements _i11.KnnRegressor {}

class _FakeLinkFunction_28 extends _i1.Fake implements _i28.LinkFunction {}

class _FakeLogisticRegressor_29 extends _i1.Fake
    implements _i11.LogisticRegressor {}

class _FakeSoftmaxRegressor_30 extends _i1.Fake
    implements _i11.SoftmaxRegressor {}

class _FakeLinearRegressor_31 extends _i1.Fake implements _i11.LinearRegressor {
}

/// A class which mocks [NumericalTreeSplitterFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockNumericalTreeSplitterFactory extends _i1.Mock
    implements _i29.NumericalTreeSplitterFactory {
  MockNumericalTreeSplitterFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NumericalTreeSplitter create() =>
      (super.noSuchMethod(Invocation.method(#create, []),
              returnValue: _FakeNumericalTreeSplitter_0())
          as _i2.NumericalTreeSplitter);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NominalTreeSplitterFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockNominalTreeSplitterFactory extends _i1.Mock
    implements _i30.NominalTreeSplitterFactory {
  MockNominalTreeSplitterFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.NominalTreeSplitter create() => (super.noSuchMethod(
      Invocation.method(#create, []),
      returnValue: _FakeNominalTreeSplitter_1()) as _i3.NominalTreeSplitter);
  @override
  String toString() => super.toString();
}

/// A class which mocks [IntermediateTreeNodeFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntermediateTreeNodeFactory extends _i1.Mock
    implements _i31.IntermediateTreeNodeFactory {
  MockIntermediateTreeNodeFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TreeNode create(_i32.TreeNodeSplittingPredicateType? predicateType,
          num? splittingValue, int? splittingIdx) =>
      (super.noSuchMethod(
          Invocation.method(
              #create, [predicateType, splittingValue, splittingIdx]),
          returnValue: _FakeTreeNode_2()) as _i4.TreeNode);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TreeSplitAssessor].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeSplitAssessor extends _i1.Mock implements _i5.TreeSplitAssessor {
  MockTreeSplitAssessor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double getAggregatedError(
          Iterable<_i9.Matrix>? splitObservations, int? targetId) =>
      (super.noSuchMethod(
          Invocation.method(#getAggregatedError, [splitObservations, targetId]),
          returnValue: 0.0) as double);
  @override
  double getError(_i9.Matrix? splitObservations, int? targetId) => (super
      .noSuchMethod(Invocation.method(#getError, [splitObservations, targetId]),
          returnValue: 0.0) as double);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TreeSplitAssessorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeSplitAssessorFactory extends _i1.Mock
    implements _i33.TreeSplitAssessorFactory {
  MockTreeSplitAssessorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TreeSplitAssessor createByType(_i34.TreeSplitAssessorType? type) =>
      (super.noSuchMethod(Invocation.method(#createByType, [type]),
          returnValue: _FakeTreeSplitAssessor_3()) as _i5.TreeSplitAssessor);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NumericalTreeSplitter].
///
/// See the documentation for Mockito's code generation for more information.
class MockNumericalTreeSplitter extends _i1.Mock
    implements _i2.NumericalTreeSplitter {
  MockNumericalTreeSplitter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<T, _i9.Matrix> split<T extends _i4.TreeNode>(
          _i9.Matrix? samples, int? splittingIdx, double? splittingValue) =>
      (super.noSuchMethod(
          Invocation.method(#split, [samples, splittingIdx, splittingValue]),
          returnValue: <T, _i9.Matrix>{}) as Map<T, _i9.Matrix>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NominalTreeSplitter].
///
/// See the documentation for Mockito's code generation for more information.
class MockNominalTreeSplitter extends _i1.Mock
    implements _i3.NominalTreeSplitter {
  MockNominalTreeSplitter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<T, _i9.Matrix> split<T extends _i4.TreeNode>(
          _i9.Matrix? samples, int? splittingIdx, List<num>? uniqueValues) =>
      (super.noSuchMethod(
          Invocation.method(#split, [samples, splittingIdx, uniqueValues]),
          returnValue: <T, _i9.Matrix>{}) as Map<T, _i9.Matrix>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TreeSplitter].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeSplitter extends _i1.Mock implements _i6.TreeSplitter {
  MockTreeSplitter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<T, _i9.Matrix> split<T extends _i4.TreeNode>(
          _i9.Matrix? samples, int? splittingIdx, int? targetId,
          [List<num>? uniqueValues]) =>
      (super.noSuchMethod(
          Invocation.method(
              #split, [samples, splittingIdx, targetId, uniqueValues]),
          returnValue: <T, _i9.Matrix>{}) as Map<T, _i9.Matrix>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TreeSplitterFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeSplitterFactory extends _i1.Mock
    implements _i35.TreeSplitterFactory {
  MockTreeSplitterFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TreeSplitter createByType(_i36.TreeSplitterType? type,
          _i34.TreeSplitAssessorType? assessorType) =>
      (super.noSuchMethod(
          Invocation.method(#createByType, [type, assessorType]),
          returnValue: _FakeTreeSplitter_4()) as _i6.TreeSplitter);
  @override
  String toString() => super.toString();
}

/// A class which mocks [MetricFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetricFactory extends _i1.Mock implements _i37.MetricFactory {
  MockMetricFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Metric createByType(_i38.MetricType? metricType) =>
      (super.noSuchMethod(Invocation.method(#createByType, [metricType]),
          returnValue: _FakeMetric_5()) as _i7.Metric);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Metric].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetric extends _i1.Mock implements _i7.Metric {
  MockMetric() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double getScore(_i9.Matrix? predictedLabels, _i9.Matrix? origLabels) => (super
      .noSuchMethod(Invocation.method(#getScore, [predictedLabels, origLabels]),
          returnValue: 0.0) as double);
  @override
  String toString() => super.toString();
}

/// A class which mocks [RandomizerFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandomizerFactory extends _i1.Mock implements _i39.RandomizerFactory {
  MockRandomizerFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Randomizer create([int? seed]) =>
      (super.noSuchMethod(Invocation.method(#create, [seed]),
          returnValue: _FakeRandomizer_6()) as _i8.Randomizer);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Randomizer].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandomizer extends _i1.Mock implements _i8.Randomizer {
  MockRandomizer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<int> getIntegerInterval(int? lowerBound, int? upperBound,
          {int? intervalLength}) =>
      (super.noSuchMethod(
          Invocation.method(#getIntegerInterval, [lowerBound, upperBound],
              {#intervalLength: intervalLength}),
          returnValue: <int>[]) as Iterable<int>);
  @override
  Iterable<double> getDoubleInterval(double? lowerBound, double? upperBound) =>
      (super.noSuchMethod(
          Invocation.method(#getDoubleInterval, [lowerBound, upperBound]),
          returnValue: <double>[]) as Iterable<double>);
  @override
  int getIntegerFromInterval(int? start, int? end) => (super.noSuchMethod(
      Invocation.method(#getIntegerFromInterval, [start, end]),
      returnValue: 0) as int);
  @override
  double getDoubleFromInterval(double? start, double? end) => (super
      .noSuchMethod(Invocation.method(#getDoubleFromInterval, [start, end]),
          returnValue: 0.0) as double);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CostFunction].
///
/// See the documentation for Mockito's code generation for more information.
class MockCostFunction extends _i1.Mock implements _i10.CostFunction {
  MockCostFunction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double getCost(_i9.Matrix? x, _i9.Matrix? w, _i9.Matrix? y) =>
      (super.noSuchMethod(Invocation.method(#getCost, [x, w, y]),
          returnValue: 0.0) as double);
  @override
  _i9.Matrix getGradient(_i9.Matrix? x, _i9.Matrix? w, _i9.Matrix? y) =>
      (super.noSuchMethod(Invocation.method(#getGradient, [x, w, y]),
          returnValue: _FakeMatrix_7()) as _i9.Matrix);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CostFunctionFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockCostFunctionFactory extends _i1.Mock
    implements _i40.CostFunctionFactory {
  MockCostFunctionFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.CostFunction createByType(_i41.CostFunctionType? type,
          {_i28.LinkFunction? linkFunction,
          num? positiveLabel,
          num? negativeLabel}) =>
      (super.noSuchMethod(
          Invocation.method(#createByType, [
            type
          ], {
            #linkFunction: linkFunction,
            #positiveLabel: positiveLabel,
            #negativeLabel: negativeLabel
          }),
          returnValue: _FakeCostFunction_8()) as _i10.CostFunction);
  @override
  String toString() => super.toString();
}

/// A class which mocks [DecisionTreeClassifierFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockDecisionTreeClassifierFactory extends _i1.Mock
    implements _i42.DecisionTreeClassifierFactory {
  MockDecisionTreeClassifierFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.DecisionTreeClassifier create(
          _i21.DataFrame? trainData,
          String? targetName,
          _i12.DType? dtype,
          num? minError,
          int? minSamplesCount,
          int? maxDepth) =>
      (super.noSuchMethod(
              Invocation.method(#create, [
                trainData,
                targetName,
                dtype,
                minError,
                minSamplesCount,
                maxDepth
              ]),
              returnValue: _FakeDecisionTreeClassifier_9())
          as _i11.DecisionTreeClassifier);
  @override
  _i11.DecisionTreeClassifier fromJson(String? json) =>
      (super.noSuchMethod(Invocation.method(#fromJson, [json]),
              returnValue: _FakeDecisionTreeClassifier_9())
          as _i11.DecisionTreeClassifier);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LinkFunction].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinkFunction extends _i1.Mock implements _i28.LinkFunction {
  MockLinkFunction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Matrix link(_i9.Matrix? scoresByClasses) =>
      (super.noSuchMethod(Invocation.method(#link, [scoresByClasses]),
          returnValue: _FakeMatrix_7()) as _i9.Matrix);
  @override
  String toString() => super.toString();
}

/// A class which mocks [InitialCoefficientsGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitialCoefficientsGenerator extends _i1.Mock
    implements _i13.InitialCoefficientsGenerator {
  MockInitialCoefficientsGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Vector generate(int? length) =>
      (super.noSuchMethod(Invocation.method(#generate, [length]),
          returnValue: _FakeVector_10()) as _i12.Vector);
  @override
  String toString() => super.toString();
}

/// A class which mocks [InitialCoefficientsGeneratorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitialCoefficientsGeneratorFactory extends _i1.Mock
    implements _i43.InitialCoefficientsGeneratorFactory {
  MockInitialCoefficientsGeneratorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.InitialCoefficientsGenerator zeroes(_i12.DType? dtype) =>
      (super.noSuchMethod(Invocation.method(#zeroes, [dtype]),
              returnValue: _FakeInitialCoefficientsGenerator_11())
          as _i13.InitialCoefficientsGenerator);
  @override
  _i13.InitialCoefficientsGenerator fromType(
          _i11.InitialCoefficientsType? type, _i12.DType? dtype) =>
      (super.noSuchMethod(Invocation.method(#fromType, [type, dtype]),
              returnValue: _FakeInitialCoefficientsGenerator_11())
          as _i13.InitialCoefficientsGenerator);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ConvergenceDetector].
///
/// See the documentation for Mockito's code generation for more information.
class MockConvergenceDetector extends _i1.Mock
    implements _i23.ConvergenceDetector {
  MockConvergenceDetector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get minDiff =>
      (super.noSuchMethod(Invocation.getter(#minDiff), returnValue: 0.0)
          as double);
  @override
  int get iterationsLimit =>
      (super.noSuchMethod(Invocation.getter(#iterationsLimit), returnValue: 0)
          as int);
  @override
  bool isConverged(double? coefficientsDiff, int? iteration) =>
      (super.noSuchMethod(
          Invocation.method(#isConverged, [coefficientsDiff, iteration]),
          returnValue: false) as bool);
  @override
  String toString() => super.toString();
}

/// A class which mocks [DistributionCalculator].
///
/// See the documentation for Mockito's code generation for more information.
class MockDistributionCalculator extends _i1.Mock
    implements _i15.DistributionCalculator {
  MockDistributionCalculator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.HashMap<T, double> calculate<T>(Iterable<T>? sequence,
          [int? classLabelsLength]) =>
      (super.noSuchMethod(
              Invocation.method(#calculate, [sequence, classLabelsLength]),
              returnValue: _FakeHashMap_12<T, double>())
          as _i14.HashMap<T, double>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [DistributionCalculatorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockDistributionCalculatorFactory extends _i1.Mock
    implements _i44.DistributionCalculatorFactory {
  MockDistributionCalculatorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.DistributionCalculator create() =>
      (super.noSuchMethod(Invocation.method(#create, []),
              returnValue: _FakeDistributionCalculator_13())
          as _i15.DistributionCalculator);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LearningRateIterableFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockLearningRateIterableFactory extends _i1.Mock
    implements _i45.LearningRateIterableFactory {
  MockLearningRateIterableFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<double> fromType(
          {_i11.LearningRateType? type,
          double? initialValue,
          double? decay,
          int? dropRate,
          int? iterationLimit}) =>
      (super.noSuchMethod(
          Invocation.method(#fromType, [], {
            #type: type,
            #initialValue: initialValue,
            #decay: decay,
            #dropRate: dropRate,
            #iterationLimit: iterationLimit
          }),
          returnValue: <double>[]) as Iterable<double>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TreeLeafDetector].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeLeafDetector extends _i1.Mock implements _i17.TreeLeafDetector {
  MockTreeLeafDetector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isLeaf(_i9.Matrix? sample, int? targetIdx,
          Iterable<int>? featureColumnIdxs, int? treeDepth) =>
      (super.noSuchMethod(
          Invocation.method(
              #isLeaf, [sample, targetIdx, featureColumnIdxs, treeDepth]),
          returnValue: false) as bool);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TreeLeafLabelFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeLeafLabelFactory extends _i1.Mock
    implements _i25.TreeLeafLabelFactory {
  MockTreeLeafLabelFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.TreeLeafLabel create(_i9.Matrix? samples, int? targetIdx) =>
      (super.noSuchMethod(Invocation.method(#create, [samples, targetIdx]),
          returnValue: _FakeTreeLeafLabel_14()) as _i16.TreeLeafLabel);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TreeLeafDetectorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeLeafDetectorFactory extends _i1.Mock
    implements _i46.TreeLeafDetectorFactory {
  MockTreeLeafDetectorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.TreeLeafDetector create(_i34.TreeSplitAssessorType? assessorType,
          num? minErrorOnNode, int? minSamplesCount, int? maxDepth) =>
      (super.noSuchMethod(
          Invocation.method(#create,
              [assessorType, minErrorOnNode, minSamplesCount, maxDepth]),
          returnValue: _FakeTreeLeafDetector_15()) as _i17.TreeLeafDetector);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ClassifierAssessor].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassifierAssessor extends _i1.Mock
    implements _i47.ClassifierAssessor {
  MockClassifierAssessor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double assess(_i48.Classifier? classifier, _i38.MetricType? metricType,
          _i21.DataFrame? samples) =>
      (super.noSuchMethod(
          Invocation.method(#assess, [classifier, metricType, samples]),
          returnValue: 0.0) as double);
  @override
  String toString() => super.toString();
}

/// A class which mocks [KnnSolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnnSolver extends _i1.Mock implements _i19.KnnSolver {
  MockKnnSolver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get k =>
      (super.noSuchMethod(Invocation.getter(#k), returnValue: 0) as int);
  @override
  _i12.Distance get distanceType =>
      (super.noSuchMethod(Invocation.getter(#distanceType),
          returnValue: _i12.Distance.euclidean) as _i12.Distance);
  @override
  Iterable<Iterable<_i49.Neighbour<_i12.Vector>>> findKNeighbours(
          _i9.Matrix? features) =>
      (super.noSuchMethod(Invocation.method(#findKNeighbours, [features]),
              returnValue: <Iterable<_i49.Neighbour<_i12.Vector>>>[])
          as Iterable<Iterable<_i49.Neighbour<_i12.Vector>>>);
  @override
  String toString() => super.toString();
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  _i50.Future<_i18.File> saveAsJson(String? filePath) =>
      (super.noSuchMethod(Invocation.method(#saveAsJson, [filePath]),
              returnValue: Future<_i18.File>.value(_FakeFile_16()))
          as _i50.Future<_i18.File>);
}

/// A class which mocks [KnnSolverFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnnSolverFactory extends _i1.Mock implements _i51.KnnSolverFactory {
  MockKnnSolverFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.KnnSolver create(_i9.Matrix? trainFeatures, _i9.Matrix? trainLabels,
          int? k, _i12.Distance? distanceType, bool? standardize) =>
      (super.noSuchMethod(
          Invocation.method(#create,
              [trainFeatures, trainLabels, k, distanceType, standardize]),
          returnValue: _FakeKnnSolver_17()) as _i19.KnnSolver);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Kernel].
///
/// See the documentation for Mockito's code generation for more information.
class MockKernel extends _i1.Mock implements _i20.Kernel {
  MockKernel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.KernelType get type => (super.noSuchMethod(Invocation.getter(#type),
      returnValue: _i11.KernelType.uniform) as _i11.KernelType);
  @override
  num getWeightByDistance(num? distance, [num? bandwidth]) =>
      (super.noSuchMethod(
          Invocation.method(#getWeightByDistance, [distance, bandwidth]),
          returnValue: 0) as num);
  @override
  String toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []), returnValue: '')
          as String);
  @override
  String toString() => super.toString();
}

/// A class which mocks [KernelFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockKernelFactory extends _i1.Mock implements _i52.KernelFactory {
  MockKernelFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Kernel createByType(_i11.KernelType? type) =>
      (super.noSuchMethod(Invocation.method(#createByType, [type]),
          returnValue: _FakeKernel_18()) as _i20.Kernel);
  @override
  String toString() => super.toString();
}

/// A class which mocks [KnnClassifierFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnnClassifierFactory extends _i1.Mock
    implements _i53.KnnClassifierFactory {
  MockKnnClassifierFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.KnnClassifier create(
          _i21.DataFrame? trainData,
          String? targetName,
          int? k,
          _i11.KernelType? kernelType,
          _i12.Distance? distance,
          String? columnPrefix,
          _i12.DType? dtype) =>
      (super.noSuchMethod(
          Invocation.method(#create, [
            trainData,
            targetName,
            k,
            kernelType,
            distance,
            columnPrefix,
            dtype
          ]),
          returnValue: _FakeKnnClassifier_19()) as _i11.KnnClassifier);
  @override
  _i11.KnnClassifier fromJson(String? json) =>
      (super.noSuchMethod(Invocation.method(#fromJson, [json]),
          returnValue: _FakeKnnClassifier_19()) as _i11.KnnClassifier);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Classifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassifier extends _i1.Mock implements _i48.Classifier {
  MockClassifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  num get positiveLabel =>
      (super.noSuchMethod(Invocation.getter(#positiveLabel), returnValue: 0)
          as num);
  @override
  num get negativeLabel =>
      (super.noSuchMethod(Invocation.getter(#negativeLabel), returnValue: 0)
          as num);
  @override
  Iterable<String> get targetNames =>
      (super.noSuchMethod(Invocation.getter(#targetNames),
          returnValue: <String>[]) as Iterable<String>);
  @override
  _i12.DType get dtype => (super.noSuchMethod(Invocation.getter(#dtype),
      returnValue: _i12.DType.float32) as _i12.DType);
  @override
  _i21.DataFrame predictProbabilities(_i21.DataFrame? testFeatures) => (super
      .noSuchMethod(Invocation.method(#predictProbabilities, [testFeatures]),
          returnValue: _FakeDataFrame_20()) as _i21.DataFrame);
  @override
  _i21.DataFrame predict(_i21.DataFrame? testFeatures) =>
      (super.noSuchMethod(Invocation.method(#predict, [testFeatures]),
          returnValue: _FakeDataFrame_20()) as _i21.DataFrame);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LinearOptimizerFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinearOptimizerFactory extends _i1.Mock
    implements _i54.LinearOptimizerFactory {
  MockLinearOptimizerFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i22.LinearOptimizer createByType(_i11.LinearOptimizerType? optimizerType,
          _i9.Matrix? points, _i9.Matrix? labels,
          {_i12.DType? dtype,
          _i10.CostFunction? costFunction,
          _i11.LearningRateType? learningRateType,
          _i11.InitialCoefficientsType? initialCoefficientsType,
          double? initialLearningRate,
          double? decay,
          int? dropRate,
          double? minCoefficientsUpdate,
          int? iterationLimit,
          double? lambda,
          int? batchSize,
          bool? isFittingDataNormalized,
          _i11.RegularizationType? regularizationType,
          int? randomSeed}) =>
      (super.noSuchMethod(
          Invocation.method(#createByType, [
            optimizerType,
            points,
            labels
          ], {
            #dtype: dtype,
            #costFunction: costFunction,
            #learningRateType: learningRateType,
            #initialCoefficientsType: initialCoefficientsType,
            #initialLearningRate: initialLearningRate,
            #decay: decay,
            #dropRate: dropRate,
            #minCoefficientsUpdate: minCoefficientsUpdate,
            #iterationLimit: iterationLimit,
            #lambda: lambda,
            #batchSize: batchSize,
            #isFittingDataNormalized: isFittingDataNormalized,
            #regularizationType: regularizationType,
            #randomSeed: randomSeed
          }),
          returnValue: _FakeLinearOptimizer_21()) as _i22.LinearOptimizer);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LinearOptimizer].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinearOptimizer extends _i1.Mock implements _i22.LinearOptimizer {
  MockLinearOptimizer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<num> get costPerIteration =>
      (super.noSuchMethod(Invocation.getter(#costPerIteration),
          returnValue: <num>[]) as List<num>);
  @override
  _i9.Matrix findExtrema(
          {_i9.Matrix? initialCoefficients,
          bool? isMinimizingObjective = true,
          bool? collectLearningData = false}) =>
      (super.noSuchMethod(
          Invocation.method(#findExtrema, [], {
            #initialCoefficients: initialCoefficients,
            #isMinimizingObjective: isMinimizingObjective,
            #collectLearningData: collectLearningData
          }),
          returnValue: _FakeMatrix_7()) as _i9.Matrix);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ConvergenceDetectorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockConvergenceDetectorFactory extends _i1.Mock
    implements _i55.ConvergenceDetectorFactory {
  MockConvergenceDetectorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.ConvergenceDetector create(double? minUpdate, int? iterationsLimit) =>
      (super.noSuchMethod(
              Invocation.method(#create, [minUpdate, iterationsLimit]),
              returnValue: _FakeConvergenceDetector_22())
          as _i23.ConvergenceDetector);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SplitIndicesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSplitIndicesProvider extends _i1.Mock
    implements _i24.SplitIndicesProvider {
  MockSplitIndicesProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<Iterable<int>> getIndices(int? numberOfSamples) =>
      (super.noSuchMethod(Invocation.method(#getIndices, [numberOfSamples]),
          returnValue: <Iterable<int>>[]) as Iterable<Iterable<int>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SplitIndicesProviderFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockSplitIndicesProviderFactory extends _i1.Mock
    implements _i56.SplitIndicesProviderFactory {
  MockSplitIndicesProviderFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.SplitIndicesProvider createByType(
          _i57.SplitIndicesProviderType? splitterType,
          {int? numberOfFolds,
          int? p}) =>
      (super.noSuchMethod(
              Invocation.method(#createByType, [splitterType],
                  {#numberOfFolds: numberOfFolds, #p: p}),
              returnValue: _FakeSplitIndicesProvider_23())
          as _i24.SplitIndicesProvider);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Assessable].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssessable extends _i1.Mock implements _i58.Assessable {
  MockAssessable() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double assess(_i21.DataFrame? observations, _i38.MetricType? metricType) =>
      (super.noSuchMethod(
          Invocation.method(#assess, [observations, metricType]),
          returnValue: 0.0) as double);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TreeLeafLabelFactoryFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeLeafLabelFactoryFactory extends _i1.Mock
    implements _i59.TreeLeafLabelFactoryFactory {
  MockTreeLeafLabelFactoryFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.TreeLeafLabelFactory createByType(_i60.TreeLeafLabelFactoryType? type) =>
      (super.noSuchMethod(Invocation.method(#createByType, [type]),
              returnValue: _FakeTreeLeafLabelFactory_24())
          as _i25.TreeLeafLabelFactory);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TreeSplitSelector].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeSplitSelector extends _i1.Mock implements _i26.TreeSplitSelector {
  MockTreeSplitSelector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<T, _i9.Matrix> select<T extends _i4.TreeNode>(
          _i9.Matrix? samples, int? targetId, Iterable<int>? featuresColumnIdxs,
          [Map<int, List<num>>? columnIdToUniqueValues]) =>
      (super.noSuchMethod(
          Invocation.method(#select,
              [samples, targetId, featuresColumnIdxs, columnIdToUniqueValues]),
          returnValue: <T, _i9.Matrix>{}) as Map<T, _i9.Matrix>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TreeSplitSelectorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeSplitSelectorFactory extends _i1.Mock
    implements _i61.TreeSplitSelectorFactory {
  MockTreeSplitSelectorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i26.TreeSplitSelector createByType(
          _i62.TreeSplitSelectorType? type,
          _i34.TreeSplitAssessorType? assessorType,
          _i36.TreeSplitterType? splitterType) =>
      (super.noSuchMethod(
          Invocation.method(#createByType, [type, assessorType, splitterType]),
          returnValue: _FakeTreeSplitSelector_25()) as _i26.TreeSplitSelector);
  @override
  String toString() => super.toString();
}

/// A class which mocks [DecisionTreeNode].
///
/// See the documentation for Mockito's code generation for more information.
class MockDecisionTreeNode extends _i1.Mock implements _i27.DecisionTreeNode {
  MockDecisionTreeNode() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get level =>
      (super.noSuchMethod(Invocation.getter(#level), returnValue: 0) as int);
  @override
  bool get isLeaf =>
      (super.noSuchMethod(Invocation.getter(#isLeaf), returnValue: false)
          as bool);
  @override
  bool get isRoot =>
      (super.noSuchMethod(Invocation.getter(#isRoot), returnValue: false)
          as bool);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  bool isSamplePassed(_i12.Vector? sample) =>
      (super.noSuchMethod(Invocation.method(#isSamplePassed, [sample]),
          returnValue: false) as bool);
  @override
  String toString() => super.toString();
}

/// A class which mocks [DecisionTreeTrainer].
///
/// See the documentation for Mockito's code generation for more information.
class MockDecisionTreeTrainer extends _i1.Mock
    implements _i63.DecisionTreeTrainer {
  MockDecisionTreeTrainer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i27.DecisionTreeNode train(_i9.Matrix? samples) =>
      (super.noSuchMethod(Invocation.method(#train, [samples]),
          returnValue: _FakeDecisionTreeNode_26()) as _i27.DecisionTreeNode);
  @override
  String toString() => super.toString();
}

/// A class which mocks [KnnClassifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnnClassifier extends _i1.Mock implements _i11.KnnClassifier {
  MockKnnClassifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get k =>
      (super.noSuchMethod(Invocation.getter(#k), returnValue: 0) as int);
  @override
  _i11.KernelType get kernelType =>
      (super.noSuchMethod(Invocation.getter(#kernelType),
          returnValue: _i11.KernelType.uniform) as _i11.KernelType);
  @override
  _i12.Distance get distanceType =>
      (super.noSuchMethod(Invocation.getter(#distanceType),
          returnValue: _i12.Distance.euclidean) as _i12.Distance);
  @override
  num get positiveLabel =>
      (super.noSuchMethod(Invocation.getter(#positiveLabel), returnValue: 0)
          as num);
  @override
  num get negativeLabel =>
      (super.noSuchMethod(Invocation.getter(#negativeLabel), returnValue: 0)
          as num);
  @override
  Iterable<String> get targetNames =>
      (super.noSuchMethod(Invocation.getter(#targetNames),
          returnValue: <String>[]) as Iterable<String>);
  @override
  _i12.DType get dtype => (super.noSuchMethod(Invocation.getter(#dtype),
      returnValue: _i12.DType.float32) as _i12.DType);
  @override
  String toString() => super.toString();
  @override
  double assess(_i21.DataFrame? observations, _i38.MetricType? metricType) =>
      (super.noSuchMethod(
          Invocation.method(#assess, [observations, metricType]),
          returnValue: 0.0) as double);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  _i50.Future<_i18.File> saveAsJson(String? filePath) =>
      (super.noSuchMethod(Invocation.method(#saveAsJson, [filePath]),
              returnValue: Future<_i18.File>.value(_FakeFile_16()))
          as _i50.Future<_i18.File>);
  @override
  _i11.KnnClassifier retrain(_i21.DataFrame? data) =>
      (super.noSuchMethod(Invocation.method(#retrain, [data]),
          returnValue: _FakeKnnClassifier_19()) as _i11.KnnClassifier);
  @override
  _i21.DataFrame predictProbabilities(_i21.DataFrame? testFeatures) => (super
      .noSuchMethod(Invocation.method(#predictProbabilities, [testFeatures]),
          returnValue: _FakeDataFrame_20()) as _i21.DataFrame);
  @override
  _i21.DataFrame predict(_i21.DataFrame? testFeatures) =>
      (super.noSuchMethod(Invocation.method(#predict, [testFeatures]),
          returnValue: _FakeDataFrame_20()) as _i21.DataFrame);
}

/// A class which mocks [KnnRegressorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnnRegressorFactory extends _i1.Mock
    implements _i64.KnnRegressorFactory {
  MockKnnRegressorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.KnnRegressor create(
          _i21.DataFrame? fittingData,
          String? targetName,
          int? k,
          _i11.KernelType? kernelType,
          _i12.Distance? distance,
          _i12.DType? dtype) =>
      (super.noSuchMethod(
          Invocation.method(#create,
              [fittingData, targetName, k, kernelType, distance, dtype]),
          returnValue: _FakeKnnRegressor_27()) as _i11.KnnRegressor);
  @override
  _i11.KnnRegressor fromJson(String? json) =>
      (super.noSuchMethod(Invocation.method(#fromJson, [json]),
          returnValue: _FakeKnnRegressor_27()) as _i11.KnnRegressor);
  @override
  String toString() => super.toString();
}

/// A class which mocks [KnnRegressor].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnnRegressor extends _i1.Mock implements _i11.KnnRegressor {
  MockKnnRegressor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get k =>
      (super.noSuchMethod(Invocation.getter(#k), returnValue: 0) as int);
  @override
  _i11.KernelType get kernelType =>
      (super.noSuchMethod(Invocation.getter(#kernelType),
          returnValue: _i11.KernelType.uniform) as _i11.KernelType);
  @override
  _i12.Distance get distanceType =>
      (super.noSuchMethod(Invocation.getter(#distanceType),
          returnValue: _i12.Distance.euclidean) as _i12.Distance);
  @override
  Iterable<String> get targetNames =>
      (super.noSuchMethod(Invocation.getter(#targetNames),
          returnValue: <String>[]) as Iterable<String>);
  @override
  _i12.DType get dtype => (super.noSuchMethod(Invocation.getter(#dtype),
      returnValue: _i12.DType.float32) as _i12.DType);
  @override
  String toString() => super.toString();
  @override
  double assess(_i21.DataFrame? observations, _i38.MetricType? metricType) =>
      (super.noSuchMethod(
          Invocation.method(#assess, [observations, metricType]),
          returnValue: 0.0) as double);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  _i50.Future<_i18.File> saveAsJson(String? filePath) =>
      (super.noSuchMethod(Invocation.method(#saveAsJson, [filePath]),
              returnValue: Future<_i18.File>.value(_FakeFile_16()))
          as _i50.Future<_i18.File>);
  @override
  _i11.KnnRegressor retrain(_i21.DataFrame? data) =>
      (super.noSuchMethod(Invocation.method(#retrain, [data]),
          returnValue: _FakeKnnRegressor_27()) as _i11.KnnRegressor);
  @override
  _i21.DataFrame predict(_i21.DataFrame? testFeatures) =>
      (super.noSuchMethod(Invocation.method(#predict, [testFeatures]),
          returnValue: _FakeDataFrame_20()) as _i21.DataFrame);
}

/// A class which mocks [LogisticRegressor].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogisticRegressor extends _i1.Mock implements _i11.LogisticRegressor {
  MockLogisticRegressor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.LinearOptimizerType get optimizerType =>
      (super.noSuchMethod(Invocation.getter(#optimizerType),
              returnValue: _i11.LinearOptimizerType.gradient)
          as _i11.LinearOptimizerType);
  @override
  int get iterationsLimit =>
      (super.noSuchMethod(Invocation.getter(#iterationsLimit), returnValue: 0)
          as int);
  @override
  double get initialLearningRate =>
      (super.noSuchMethod(Invocation.getter(#initialLearningRate),
          returnValue: 0.0) as double);
  @override
  double get decay =>
      (super.noSuchMethod(Invocation.getter(#decay), returnValue: 0.0)
          as double);
  @override
  int get dropRate =>
      (super.noSuchMethod(Invocation.getter(#dropRate), returnValue: 0) as int);
  @override
  double get minCoefficientsUpdate =>
      (super.noSuchMethod(Invocation.getter(#minCoefficientsUpdate),
          returnValue: 0.0) as double);
  @override
  num get probabilityThreshold =>
      (super.noSuchMethod(Invocation.getter(#probabilityThreshold),
          returnValue: 0) as num);
  @override
  double get lambda =>
      (super.noSuchMethod(Invocation.getter(#lambda), returnValue: 0.0)
          as double);
  @override
  int get batchSize =>
      (super.noSuchMethod(Invocation.getter(#batchSize), returnValue: 0)
          as int);
  @override
  bool get isFittingDataNormalized =>
      (super.noSuchMethod(Invocation.getter(#isFittingDataNormalized),
          returnValue: false) as bool);
  @override
  _i11.LearningRateType get learningRateType =>
      (super.noSuchMethod(Invocation.getter(#learningRateType),
              returnValue: _i11.LearningRateType.decreasingAdaptive)
          as _i11.LearningRateType);
  @override
  _i11.InitialCoefficientsType get initialCoefficientsType =>
      (super.noSuchMethod(Invocation.getter(#initialCoefficientsType),
              returnValue: _i11.InitialCoefficientsType.zeroes)
          as _i11.InitialCoefficientsType);
  @override
  _i28.LinkFunction get linkFunction =>
      (super.noSuchMethod(Invocation.getter(#linkFunction),
          returnValue: _FakeLinkFunction_28()) as _i28.LinkFunction);
  @override
  bool get fitIntercept =>
      (super.noSuchMethod(Invocation.getter(#fitIntercept), returnValue: false)
          as bool);
  @override
  num get interceptScale =>
      (super.noSuchMethod(Invocation.getter(#interceptScale), returnValue: 0)
          as num);
  @override
  _i9.Matrix get coefficientsByClasses =>
      (super.noSuchMethod(Invocation.getter(#coefficientsByClasses),
          returnValue: _FakeMatrix_7()) as _i9.Matrix);
  @override
  num get positiveLabel =>
      (super.noSuchMethod(Invocation.getter(#positiveLabel), returnValue: 0)
          as num);
  @override
  num get negativeLabel =>
      (super.noSuchMethod(Invocation.getter(#negativeLabel), returnValue: 0)
          as num);
  @override
  Iterable<String> get targetNames =>
      (super.noSuchMethod(Invocation.getter(#targetNames),
          returnValue: <String>[]) as Iterable<String>);
  @override
  _i12.DType get dtype => (super.noSuchMethod(Invocation.getter(#dtype),
      returnValue: _i12.DType.float32) as _i12.DType);
  @override
  String toString() => super.toString();
  @override
  double assess(_i21.DataFrame? observations, _i38.MetricType? metricType) =>
      (super.noSuchMethod(
          Invocation.method(#assess, [observations, metricType]),
          returnValue: 0.0) as double);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  _i50.Future<_i18.File> saveAsJson(String? filePath) =>
      (super.noSuchMethod(Invocation.method(#saveAsJson, [filePath]),
              returnValue: Future<_i18.File>.value(_FakeFile_16()))
          as _i50.Future<_i18.File>);
  @override
  _i11.LogisticRegressor retrain(_i21.DataFrame? data) =>
      (super.noSuchMethod(Invocation.method(#retrain, [data]),
          returnValue: _FakeLogisticRegressor_29()) as _i11.LogisticRegressor);
  @override
  _i21.DataFrame predictProbabilities(_i21.DataFrame? testFeatures) => (super
      .noSuchMethod(Invocation.method(#predictProbabilities, [testFeatures]),
          returnValue: _FakeDataFrame_20()) as _i21.DataFrame);
  @override
  _i21.DataFrame predict(_i21.DataFrame? testFeatures) =>
      (super.noSuchMethod(Invocation.method(#predict, [testFeatures]),
          returnValue: _FakeDataFrame_20()) as _i21.DataFrame);
}

/// A class which mocks [SoftmaxRegressor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoftmaxRegressor extends _i1.Mock implements _i11.SoftmaxRegressor {
  MockSoftmaxRegressor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.LinearOptimizerType get optimizerType =>
      (super.noSuchMethod(Invocation.getter(#optimizerType),
              returnValue: _i11.LinearOptimizerType.gradient)
          as _i11.LinearOptimizerType);
  @override
  int get iterationsLimit =>
      (super.noSuchMethod(Invocation.getter(#iterationsLimit), returnValue: 0)
          as int);
  @override
  double get initialLearningRate =>
      (super.noSuchMethod(Invocation.getter(#initialLearningRate),
          returnValue: 0.0) as double);
  @override
  double get decay =>
      (super.noSuchMethod(Invocation.getter(#decay), returnValue: 0.0)
          as double);
  @override
  int get dropRate =>
      (super.noSuchMethod(Invocation.getter(#dropRate), returnValue: 0) as int);
  @override
  double get minCoefficientsUpdate =>
      (super.noSuchMethod(Invocation.getter(#minCoefficientsUpdate),
          returnValue: 0.0) as double);
  @override
  double get lambda =>
      (super.noSuchMethod(Invocation.getter(#lambda), returnValue: 0.0)
          as double);
  @override
  int get batchSize =>
      (super.noSuchMethod(Invocation.getter(#batchSize), returnValue: 0)
          as int);
  @override
  bool get isFittingDataNormalized =>
      (super.noSuchMethod(Invocation.getter(#isFittingDataNormalized),
          returnValue: false) as bool);
  @override
  _i11.LearningRateType get learningRateType =>
      (super.noSuchMethod(Invocation.getter(#learningRateType),
              returnValue: _i11.LearningRateType.decreasingAdaptive)
          as _i11.LearningRateType);
  @override
  _i11.InitialCoefficientsType get initialCoefficientsType =>
      (super.noSuchMethod(Invocation.getter(#initialCoefficientsType),
              returnValue: _i11.InitialCoefficientsType.zeroes)
          as _i11.InitialCoefficientsType);
  @override
  _i28.LinkFunction get linkFunction =>
      (super.noSuchMethod(Invocation.getter(#linkFunction),
          returnValue: _FakeLinkFunction_28()) as _i28.LinkFunction);
  @override
  bool get fitIntercept =>
      (super.noSuchMethod(Invocation.getter(#fitIntercept), returnValue: false)
          as bool);
  @override
  num get interceptScale =>
      (super.noSuchMethod(Invocation.getter(#interceptScale), returnValue: 0)
          as num);
  @override
  _i9.Matrix get coefficientsByClasses =>
      (super.noSuchMethod(Invocation.getter(#coefficientsByClasses),
          returnValue: _FakeMatrix_7()) as _i9.Matrix);
  @override
  num get positiveLabel =>
      (super.noSuchMethod(Invocation.getter(#positiveLabel), returnValue: 0)
          as num);
  @override
  num get negativeLabel =>
      (super.noSuchMethod(Invocation.getter(#negativeLabel), returnValue: 0)
          as num);
  @override
  Iterable<String> get targetNames =>
      (super.noSuchMethod(Invocation.getter(#targetNames),
          returnValue: <String>[]) as Iterable<String>);
  @override
  _i12.DType get dtype => (super.noSuchMethod(Invocation.getter(#dtype),
      returnValue: _i12.DType.float32) as _i12.DType);
  @override
  String toString() => super.toString();
  @override
  double assess(_i21.DataFrame? observations, _i38.MetricType? metricType) =>
      (super.noSuchMethod(
          Invocation.method(#assess, [observations, metricType]),
          returnValue: 0.0) as double);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  _i50.Future<_i18.File> saveAsJson(String? filePath) =>
      (super.noSuchMethod(Invocation.method(#saveAsJson, [filePath]),
              returnValue: Future<_i18.File>.value(_FakeFile_16()))
          as _i50.Future<_i18.File>);
  @override
  _i11.SoftmaxRegressor retrain(_i21.DataFrame? data) =>
      (super.noSuchMethod(Invocation.method(#retrain, [data]),
          returnValue: _FakeSoftmaxRegressor_30()) as _i11.SoftmaxRegressor);
  @override
  _i21.DataFrame predictProbabilities(_i21.DataFrame? testFeatures) => (super
      .noSuchMethod(Invocation.method(#predictProbabilities, [testFeatures]),
          returnValue: _FakeDataFrame_20()) as _i21.DataFrame);
  @override
  _i21.DataFrame predict(_i21.DataFrame? testFeatures) =>
      (super.noSuchMethod(Invocation.method(#predict, [testFeatures]),
          returnValue: _FakeDataFrame_20()) as _i21.DataFrame);
}

/// A class which mocks [SoftmaxRegressorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoftmaxRegressorFactory extends _i1.Mock
    implements _i65.SoftmaxRegressorFactory {
  MockSoftmaxRegressorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.SoftmaxRegressor create(
          {_i21.DataFrame? trainData,
          Iterable<String>? targetNames,
          _i11.LinearOptimizerType? optimizerType,
          int? iterationsLimit,
          double? initialLearningRate,
          double? decay,
          int? dropRate,
          double? minCoefficientsUpdate,
          double? lambda,
          int? batchSize,
          bool? fitIntercept,
          double? interceptScale,
          _i11.LearningRateType? learningRateType,
          bool? isFittingDataNormalized,
          _i11.InitialCoefficientsType? initialCoefficientsType,
          num? positiveLabel,
          num? negativeLabel,
          bool? collectLearningData,
          _i12.DType? dtype,
          _i11.RegularizationType? regularizationType,
          _i9.Matrix? initialCoefficients,
          int? randomSeed}) =>
      (super.noSuchMethod(
          Invocation.method(#create, [], {
            #trainData: trainData,
            #targetNames: targetNames,
            #optimizerType: optimizerType,
            #iterationsLimit: iterationsLimit,
            #initialLearningRate: initialLearningRate,
            #decay: decay,
            #dropRate: dropRate,
            #minCoefficientsUpdate: minCoefficientsUpdate,
            #lambda: lambda,
            #batchSize: batchSize,
            #fitIntercept: fitIntercept,
            #interceptScale: interceptScale,
            #learningRateType: learningRateType,
            #isFittingDataNormalized: isFittingDataNormalized,
            #initialCoefficientsType: initialCoefficientsType,
            #positiveLabel: positiveLabel,
            #negativeLabel: negativeLabel,
            #collectLearningData: collectLearningData,
            #dtype: dtype,
            #regularizationType: regularizationType,
            #initialCoefficients: initialCoefficients,
            #randomSeed: randomSeed
          }),
          returnValue: _FakeSoftmaxRegressor_30()) as _i11.SoftmaxRegressor);
  @override
  _i11.SoftmaxRegressor fromJson(String? json) =>
      (super.noSuchMethod(Invocation.method(#fromJson, [json]),
          returnValue: _FakeSoftmaxRegressor_30()) as _i11.SoftmaxRegressor);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Predictor].
///
/// See the documentation for Mockito's code generation for more information.
class MockPredictor extends _i1.Mock implements _i66.Predictor {
  MockPredictor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<String> get targetNames =>
      (super.noSuchMethod(Invocation.getter(#targetNames),
          returnValue: <String>[]) as Iterable<String>);
  @override
  _i12.DType get dtype => (super.noSuchMethod(Invocation.getter(#dtype),
      returnValue: _i12.DType.float32) as _i12.DType);
  @override
  _i21.DataFrame predict(_i21.DataFrame? testFeatures) =>
      (super.noSuchMethod(Invocation.method(#predict, [testFeatures]),
          returnValue: _FakeDataFrame_20()) as _i21.DataFrame);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LinearRegressorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinearRegressorFactory extends _i1.Mock
    implements _i67.LinearRegressorFactory {
  MockLinearRegressorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.LinearRegressor create(
          {_i21.DataFrame? fittingData,
          String? targetName,
          _i11.LinearOptimizerType? optimizerType,
          int? iterationsLimit,
          _i11.LearningRateType? learningRateType,
          _i11.InitialCoefficientsType? initialCoefficientsType,
          double? initialLearningRate,
          double? decay,
          int? dropRate,
          double? minCoefficientsUpdate,
          double? lambda,
          bool? fitIntercept,
          double? interceptScale,
          int? batchSize,
          bool? isFittingDataNormalized,
          bool? collectLearningData,
          _i12.DType? dtype,
          _i11.RegularizationType? regularizationType,
          int? randomSeed,
          _i9.Matrix? initialCoefficients}) =>
      (super.noSuchMethod(
          Invocation.method(#create, [], {
            #fittingData: fittingData,
            #targetName: targetName,
            #optimizerType: optimizerType,
            #iterationsLimit: iterationsLimit,
            #learningRateType: learningRateType,
            #initialCoefficientsType: initialCoefficientsType,
            #initialLearningRate: initialLearningRate,
            #decay: decay,
            #dropRate: dropRate,
            #minCoefficientsUpdate: minCoefficientsUpdate,
            #lambda: lambda,
            #fitIntercept: fitIntercept,
            #interceptScale: interceptScale,
            #batchSize: batchSize,
            #isFittingDataNormalized: isFittingDataNormalized,
            #collectLearningData: collectLearningData,
            #dtype: dtype,
            #regularizationType: regularizationType,
            #randomSeed: randomSeed,
            #initialCoefficients: initialCoefficients
          }),
          returnValue: _FakeLinearRegressor_31()) as _i11.LinearRegressor);
  @override
  _i11.LinearRegressor fromJson(String? json) =>
      (super.noSuchMethod(Invocation.method(#fromJson, [json]),
          returnValue: _FakeLinearRegressor_31()) as _i11.LinearRegressor);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LinearRegressor].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinearRegressor extends _i1.Mock implements _i11.LinearRegressor {
  MockLinearRegressor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.LinearOptimizerType get optimizerType =>
      (super.noSuchMethod(Invocation.getter(#optimizerType),
              returnValue: _i11.LinearOptimizerType.gradient)
          as _i11.LinearOptimizerType);
  @override
  int get iterationsLimit =>
      (super.noSuchMethod(Invocation.getter(#iterationsLimit), returnValue: 0)
          as int);
  @override
  _i11.LearningRateType get learningRateType =>
      (super.noSuchMethod(Invocation.getter(#learningRateType),
              returnValue: _i11.LearningRateType.decreasingAdaptive)
          as _i11.LearningRateType);
  @override
  _i11.InitialCoefficientsType get initialCoefficientsType =>
      (super.noSuchMethod(Invocation.getter(#initialCoefficientsType),
              returnValue: _i11.InitialCoefficientsType.zeroes)
          as _i11.InitialCoefficientsType);
  @override
  num get initialLearningRate => (super
          .noSuchMethod(Invocation.getter(#initialLearningRate), returnValue: 0)
      as num);
  @override
  num get decay =>
      (super.noSuchMethod(Invocation.getter(#decay), returnValue: 0) as num);
  @override
  int get dropRate =>
      (super.noSuchMethod(Invocation.getter(#dropRate), returnValue: 0) as int);
  @override
  num get minCoefficientsUpdate =>
      (super.noSuchMethod(Invocation.getter(#minCoefficientsUpdate),
          returnValue: 0) as num);
  @override
  num get lambda =>
      (super.noSuchMethod(Invocation.getter(#lambda), returnValue: 0) as num);
  @override
  int get batchSize =>
      (super.noSuchMethod(Invocation.getter(#batchSize), returnValue: 0)
          as int);
  @override
  bool get isFittingDataNormalized =>
      (super.noSuchMethod(Invocation.getter(#isFittingDataNormalized),
          returnValue: false) as bool);
  @override
  _i12.Vector get coefficients =>
      (super.noSuchMethod(Invocation.getter(#coefficients),
          returnValue: _FakeVector_10()) as _i12.Vector);
  @override
  String get targetName =>
      (super.noSuchMethod(Invocation.getter(#targetName), returnValue: '')
          as String);
  @override
  bool get fitIntercept =>
      (super.noSuchMethod(Invocation.getter(#fitIntercept), returnValue: false)
          as bool);
  @override
  num get interceptScale =>
      (super.noSuchMethod(Invocation.getter(#interceptScale), returnValue: 0)
          as num);
  @override
  Iterable<String> get targetNames =>
      (super.noSuchMethod(Invocation.getter(#targetNames),
          returnValue: <String>[]) as Iterable<String>);
  @override
  _i12.DType get dtype => (super.noSuchMethod(Invocation.getter(#dtype),
      returnValue: _i12.DType.float32) as _i12.DType);
  @override
  String toString() => super.toString();
  @override
  double assess(_i21.DataFrame? observations, _i38.MetricType? metricType) =>
      (super.noSuchMethod(
          Invocation.method(#assess, [observations, metricType]),
          returnValue: 0.0) as double);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  _i50.Future<_i18.File> saveAsJson(String? filePath) =>
      (super.noSuchMethod(Invocation.method(#saveAsJson, [filePath]),
              returnValue: Future<_i18.File>.value(_FakeFile_16()))
          as _i50.Future<_i18.File>);
  @override
  _i11.LinearRegressor retrain(_i21.DataFrame? data) =>
      (super.noSuchMethod(Invocation.method(#retrain, [data]),
          returnValue: _FakeLinearRegressor_31()) as _i11.LinearRegressor);
  @override
  _i21.DataFrame predict(_i21.DataFrame? testFeatures) =>
      (super.noSuchMethod(Invocation.method(#predict, [testFeatures]),
          returnValue: _FakeDataFrame_20()) as _i21.DataFrame);
}

/// A class which mocks [DecisionTreeClassifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockDecisionTreeClassifier extends _i1.Mock
    implements _i11.DecisionTreeClassifier {
  MockDecisionTreeClassifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  num get minError =>
      (super.noSuchMethod(Invocation.getter(#minError), returnValue: 0) as num);
  @override
  int get minSamplesCount =>
      (super.noSuchMethod(Invocation.getter(#minSamplesCount), returnValue: 0)
          as int);
  @override
  int get maxDepth =>
      (super.noSuchMethod(Invocation.getter(#maxDepth), returnValue: 0) as int);
  @override
  num get positiveLabel =>
      (super.noSuchMethod(Invocation.getter(#positiveLabel), returnValue: 0)
          as num);
  @override
  num get negativeLabel =>
      (super.noSuchMethod(Invocation.getter(#negativeLabel), returnValue: 0)
          as num);
  @override
  Iterable<String> get targetNames =>
      (super.noSuchMethod(Invocation.getter(#targetNames),
          returnValue: <String>[]) as Iterable<String>);
  @override
  _i12.DType get dtype => (super.noSuchMethod(Invocation.getter(#dtype),
      returnValue: _i12.DType.float32) as _i12.DType);
  @override
  String toString() => super.toString();
  @override
  double assess(_i21.DataFrame? observations, _i38.MetricType? metricType) =>
      (super.noSuchMethod(
          Invocation.method(#assess, [observations, metricType]),
          returnValue: 0.0) as double);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  _i50.Future<_i18.File> saveAsJson(String? filePath) =>
      (super.noSuchMethod(Invocation.method(#saveAsJson, [filePath]),
              returnValue: Future<_i18.File>.value(_FakeFile_16()))
          as _i50.Future<_i18.File>);
  @override
  _i11.DecisionTreeClassifier retrain(_i21.DataFrame? data) =>
      (super.noSuchMethod(Invocation.method(#retrain, [data]),
              returnValue: _FakeDecisionTreeClassifier_9())
          as _i11.DecisionTreeClassifier);
  @override
  _i21.DataFrame predictProbabilities(_i21.DataFrame? testFeatures) => (super
      .noSuchMethod(Invocation.method(#predictProbabilities, [testFeatures]),
          returnValue: _FakeDataFrame_20()) as _i21.DataFrame);
  @override
  _i21.DataFrame predict(_i21.DataFrame? testFeatures) =>
      (super.noSuchMethod(Invocation.method(#predict, [testFeatures]),
          returnValue: _FakeDataFrame_20()) as _i21.DataFrame);
}

/// A class which mocks [LogisticRegressorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogisticRegressorFactory extends _i1.Mock
    implements _i68.LogisticRegressorFactory {
  MockLogisticRegressorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.LogisticRegressor create(
          {_i21.DataFrame? trainData,
          String? targetName,
          _i11.LinearOptimizerType? optimizerType,
          int? iterationsLimit,
          double? initialLearningRate,
          double? decay,
          int? dropRate,
          double? minCoefficientsUpdate,
          double? probabilityThreshold,
          double? lambda,
          int? batchSize,
          bool? fitIntercept,
          double? interceptScale,
          bool? isFittingDataNormalized,
          _i11.LearningRateType? learningRateType,
          _i11.InitialCoefficientsType? initialCoefficientsType,
          num? positiveLabel,
          num? negativeLabel,
          bool? collectLearningData,
          _i12.DType? dtype,
          _i11.RegularizationType? regularizationType,
          _i12.Vector? initialCoefficients,
          int? randomSeed}) =>
      (super.noSuchMethod(
          Invocation.method(#create, [], {
            #trainData: trainData,
            #targetName: targetName,
            #optimizerType: optimizerType,
            #iterationsLimit: iterationsLimit,
            #initialLearningRate: initialLearningRate,
            #decay: decay,
            #dropRate: dropRate,
            #minCoefficientsUpdate: minCoefficientsUpdate,
            #probabilityThreshold: probabilityThreshold,
            #lambda: lambda,
            #batchSize: batchSize,
            #fitIntercept: fitIntercept,
            #interceptScale: interceptScale,
            #isFittingDataNormalized: isFittingDataNormalized,
            #learningRateType: learningRateType,
            #initialCoefficientsType: initialCoefficientsType,
            #positiveLabel: positiveLabel,
            #negativeLabel: negativeLabel,
            #collectLearningData: collectLearningData,
            #dtype: dtype,
            #regularizationType: regularizationType,
            #initialCoefficients: initialCoefficients,
            #randomSeed: randomSeed
          }),
          returnValue: _FakeLogisticRegressor_29()) as _i11.LogisticRegressor);
  @override
  _i11.LogisticRegressor fromJson(String? json) =>
      (super.noSuchMethod(Invocation.method(#fromJson, [json]),
          returnValue: _FakeLogisticRegressor_29()) as _i11.LogisticRegressor);
  @override
  String toString() => super.toString();
}
