include: package:pedantic/analysis_options.yaml

linter:
  rules:
    non_constant_identifier_names: false

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
  errors:
    unnecessary_import: error
    unnecessary_type_check: error
    missing_return: error
    dead_code: error
    duplicate_import: error
    unused_import: error
