targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false
          checked: true
          create_to_json: true
          disallow_unrecognized_keys: true
          explicit_to_json: false
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
          nullable: true

      inject_generator:
        generate_for:
          - "lib/**/*.summary"
          - "lib/**/*_impl.dart"
          - "lib/**/*_module.dart"
          - "lib/**/*_injector.dart"
